# Generated by Django 5.2.5 on 2025-11-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_add_community'),
        ('posts', '0007_comment_deleted_at_comment_deleted_by_and_more'),
    ]

    operations = [
    ]
