# Generated by Django 5.2.5 on 2025-11-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_merge_20251101_0722'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='posts_comme_communi_f9556a_idx',
            old_name='posts_comm_communi_0a92b6_idx',
        ),
    ]
