# Generated by Django 5.2.5 on 2025-11-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_single_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
