# Generated by Django 5.2.5 on 2025-11-06 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_comment_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expires_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
