# Generated by Django 5.2.5 on 2025-11-07 14:32

from django.db import migrations, models
from django.db.models import Count


def populate_votes_total(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    Comment = apps.get_model('posts', 'Comment')
    PostVote = apps.get_model('posts', 'PostVote')
    CommentVote = apps.get_model('posts', 'CommentVote')

    post_totals = PostVote.objects.values('post_id').annotate(total=Count('id'))
    for entry in post_totals:
        Post.objects.filter(pk=entry['post_id']).update(votes_total=entry['total'])

    comment_totals = CommentVote.objects.values('comment_id').annotate(total=Count('id'))
    for entry in comment_totals:
        Comment.objects.filter(pk=entry['comment_id']).update(votes_total=entry['total'])


def reverse_populate_votes_total(apps, schema_editor):
    # 逆適用時は0にリセット
    Post = apps.get_model('posts', 'Post')
    Comment = apps.get_model('posts', 'Comment')
    Post.objects.update(votes_total=0)
    Comment.objects.update(votes_total=0)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_poll_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='votes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='votes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_votes_total, reverse_populate_votes_total),
    ]
