# Generated by Django 5.2.5 on 2025-11-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_post_post_type_postmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, help_text='コメント作成時のIPアドレス', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_ip',
            field=models.GenericIPAddressField(blank=True, help_text='投稿作成時のIPアドレス', null=True),
        ),
    ]
