# Generated by Django 5.2.5 on 2025-10-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='join_policy',
            field=models.CharField(choices=[('open', 'Open'), ('approval', 'Approval Required'), ('invite', 'Invite Only'), ('login', 'Login Users Only')], default='open', max_length=16),
        ),
    ]
