# Generated by Django 5.2.5 on 2025-11-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_communitytag'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='communityblock',
            new_name='communities_communi_ddb4dd_idx',
            old_name='communities_community_user_idx',
        ),
        migrations.RenameIndex(
            model_name='communitytag',
            new_name='communities_communi_3dbb14_idx',
            old_name='communities_community_id_name_idx',
        ),
    ]
