# Generated by Django 5.2.5 on 2025-11-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_rename_communities_community_user_idx_communities_communi_ddb4dd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitytag',
            name='permission_scope',
        ),
        migrations.AddField(
            model_name='community',
            name='tag_permission_scope',
            field=models.CharField(choices=[('all', 'All Participants'), ('moderator', 'Moderators'), ('owner', 'Owner')], default='all', max_length=16),
        ),
    ]
