# Generated by Django 5.2.5 on 2025-11-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_remove_communitytag_permission_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytag',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
