# Generated by Django 5.2.5 on 2025-11-03 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_alter_communitytag_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='appointed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_standard_moderators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin_moderator', 'AdminModerator'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=16),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'appointed_by_admin'], name='communities_communi_87f456_idx'),
        ),
        migrations.AddConstraint(
            model_name='communitymembership',
            constraint=models.CheckConstraint(condition=models.Q(('appointed_by_admin__isnull', True), ('role', 'moderator'), _connector='OR'), name='appointed_by_admin_requires_standard_moderator'),
        ),
    ]
