# Generated by Django 5.2.5 on 2025-01-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_communitymute'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='allow_repost',
            field=models.BooleanField(default=False),
        ),
    ]
