# Generated by Django 5.2.5 on 2025-11-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_add_community_allow_repost'),
        ('posts', '0018_postfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='clip_post',
            field=models.ForeignKey(blank=True, help_text='コミュニティに固定されたポスト', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clipped_in_communities', to='posts.post'),
        ),
    ]
