# Generated by Django 5.2.5 on 2025-11-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_community_clip_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='karma',
            field=models.IntegerField(default=0, help_text='ゲストユーザーが投票するために必要な最小スコア'),
        ),
    ]
