# Generated by Django 5.2.5 on 2025-11-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0015_add_is_deleted_to_community'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='community',
            new_name='communities_is_dele_3ab054_idx',
            old_name='communities_is_dele_idx',
        ),
    ]
