# Generated by Django 5.2.5 on 2025-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
