# Generated by Django 5.2.5 on 2025-11-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post_comment', 'ポストへのコメント'), ('followed_post_comment', 'フォローしたスレッドへのコメント'), ('comment_reply', 'コメントへの返信'), ('comment_deleted', 'コメントの削除'), ('admin_notification', '運営通知'), ('report_created', '報告の作成')], max_length=32),
        ),
    ]
