# Generated by Django 5.2.5 on 2025-11-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='最後にログインした時のIPアドレス', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, help_text='登録時のIPアドレス', null=True),
        ),
    ]
