# Generated by Django 5.2.5 on 2025-11-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_ensure_userprofile_for_all_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
    ]
