"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 環境変数の読み込み順序を修正：
# 1. まず.env.prodファイルが存在するか確認（本番環境の可能性が高い）
# 2. 存在する場合は先に読み込む（override=Falseで既存の環境変数を優先）
# 3. その後でENVIRONMENTを判定する
env_prod_file = BASE_DIR / '.env.prod'
env_dev_file = BASE_DIR / '.env.dev'

# 環境変数ENVIRONMENTを先に取得（docker-composeなどで設定されている場合）
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')

# .env.prodファイルが存在する場合は先に読み込む
# override=False: 既存の環境変数を優先（docker-composeなどで設定されている場合）
# これにより、docker-composeで設定されたENVIRONMENT=productionが優先される
if env_prod_file.exists():
    load_dotenv(env_prod_file, override=False)
    # .env.prodファイルが存在し、ENVIRONMENTが設定されていない場合は本番環境と判断
    if not os.getenv('ENVIRONMENT'):
        ENVIRONMENT = 'production'
elif env_dev_file.exists():
    load_dotenv(env_dev_file, override=False)

# .envファイルを読み込んだ後、再度ENVIRONMENTを取得
# （.env.prodや.env.devから読み込まれた可能性がある）
ENVIRONMENT = os.getenv('ENVIRONMENT', ENVIRONMENT)

# 本番環境の検出: ENVIRONMENT環境変数が設定されていない場合でも、
# ドメイン名から推測（api.anonium.netなど）
if ENVIRONMENT == 'development':
    allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
    if allowed_hosts_env:
        allowed_hosts_check = allowed_hosts_env.lower()
        if 'anonium.net' in allowed_hosts_check or 'api.anonium.net' in allowed_hosts_check:
            ENVIRONMENT = 'production'

# 本番環境では.env.prodが存在しない場合、環境変数から直接読み込む
# Cloud Runなどでは環境変数が直接設定されるため

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-pm4o%_k#&hnja$3g)@c(0@@l#s4@vd1@3wmi*fw7m_od%q4ky3')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# ALLOWED_HOSTS
# 本番環境のデフォルト値を追加（環境変数が設定されていない場合のフォールバック）
if ENVIRONMENT == 'production':
    default_allowed_hosts = 'localhost,127.0.0.1,backend,0.0.0.0,api.anonium.net'
else:
    default_allowed_hosts = 'localhost,127.0.0.1,backend,0.0.0.0'
allowed_hosts_str = os.getenv('ALLOWED_HOSTS', default_allowed_hosts)
# 空文字列の場合はデフォルト値を使用
if not allowed_hosts_str or allowed_hosts_str.strip() == '':
    allowed_hosts_str = default_allowed_hosts
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]

# WebSocket/Channelsの有効化フラグ（本番環境では無効化）
ENABLE_WEBSOCKET = os.getenv('ENABLE_WEBSOCKET', 'False').lower() == 'true'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Local apps
    'app',  # 管理コマンドを使用するために追加
    'accounts',
    'communities',
    'posts',
    'messages',
]

# WebSocketが有効な場合のみchannelsを追加
if ENABLE_WEBSOCKET:
    INSTALLED_APPS.insert(3, 'channels')  # channelsを適切な位置に挿入

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# WebSocketが有効な場合のみASGI_APPLICATIONを設定
if ENABLE_WEBSOCKET:
    ASGI_APPLICATION = 'app.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# データベース設定を環境変数から読み込む
DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')
DB_NAME = os.getenv('DB_NAME', str(BASE_DIR / 'db.sqlite3'))
DB_USER = os.getenv('DB_USER', '')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_HOST = os.getenv('DB_HOST', '')
DB_PORT = os.getenv('DB_PORT', '')

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
else:
    # SQLite（開発環境用）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'ja')
TIME_ZONE = os.getenv('TIME_ZONE', 'Asia/Tokyo')
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATIC_ROOT = os.getenv('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))

# Media files
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media'))

# Google Cloud Storage Settings
GCS_ENABLED = os.getenv('GCS_ENABLED', 'False').lower() == 'true'
GCS_BUCKET_NAME = os.getenv('GCS_BUCKET_NAME', '')
GCS_PROJECT_ID = os.getenv('GCS_PROJECT_ID', '')
# サービスアカウントのJSONキーファイルのパス、または環境変数で認証情報を設定
GCS_CREDENTIALS_PATH = os.getenv('GCS_CREDENTIALS_PATH', '')  # 例: /path/to/service-account-key.json
# 公開URL（カスタムドメインまたはstorage.googleapis.com）
GCS_PUBLIC_URL = os.getenv('GCS_PUBLIC_URL', '')  # 例: https://storage.googleapis.com/bucket-name または https://cdn.example.com

# Cloudflare Workers Cache Invalidation Settings
# Workersは削除され、バックエンドに直接接続する構成に変更されました
# WORKERS_URL = os.getenv('WORKERS_URL', 'http://workers:8787')  # 削除済み
# CACHE_INVALIDATION_TOKEN = os.getenv('CACHE_INVALIDATION_TOKEN', '')  # 削除済み

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.CookieJWTAuthentication',  # CookieからJWTトークンを読み取る
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # 後方互換性のため残す（Authorizationヘッダーからも読み取り可能）
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': int(os.getenv('PAGE_SIZE', '20')),
    # DRFではCSRF保護を無効化（JWT認証を使用するため）
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Simple JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME_HOURS', '24'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME_DAYS', '7'))),
}

# CORS settings
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'True').lower() == 'true'
# 本番環境のデフォルト値を追加（環境変数が設定されていない場合のフォールバック）
if ENVIRONMENT == 'production':
    default_cors_origins = 'https://www.anonium.net,http://localhost:3000'
else:
    default_cors_origins = 'http://localhost:3000'
cors_origins_str = os.getenv('CORS_ALLOWED_ORIGINS', default_cors_origins)
# 空文字列の場合はデフォルト値を使用
if not cors_origins_str or cors_origins_str.strip() == '':
    cors_origins_str = default_cors_origins
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_str.split(',') if origin.strip()]

# CSRF設定（DRFでは通常無効化されるが、念のため設定）
# DRFのAPIViewは自動的にCSRFを無効化するが、CORSリクエストのために設定
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()
CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()])

# Django Channels settings (WebSocketが有効な場合のみ)
if ENABLE_WEBSOCKET:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
            # 本番環境では以下のようにRedisを使用:
            # 'BACKEND': 'channels_redis.core.RedisChannelLayer',
            # 'CONFIG': {
            #     "hosts": [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')],
            # },
        },
    }
else:
    # WebSocketが無効な場合は空の設定
    CHANNEL_LAYERS = {}

# Email settings (Amazon SES SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'email-smtp.us-east-1.amazonaws.com')  # Amazon SES SMTP endpoint
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')  # SMTP username
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # SMTP password
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')  # 送信元メールアドレス
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Frontend URL (for email verification links)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Google OAuth 2.0 Settings
GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', '')
GOOGLE_OAUTH_REDIRECT_URI = os.getenv('GOOGLE_OAUTH_REDIRECT_URI', f'{FRONTEND_URL}/auth/google/callback')
GOOGLE_OAUTH_AUTHORIZE_URL = 'https://accounts.google.com/o/oauth2/v2/auth'
GOOGLE_OAUTH_TOKEN_URL = 'https://oauth2.googleapis.com/token'
GOOGLE_OAUTH_USER_INFO_URL = 'https://www.googleapis.com/oauth2/v2/userinfo'

# X (Twitter) OAuth 2.0 Settings
X_OAUTH_CLIENT_ID = os.getenv('X_OAUTH_CLIENT_ID', '')
X_OAUTH_CLIENT_SECRET = os.getenv('X_OAUTH_CLIENT_SECRET', '')
X_OAUTH_REDIRECT_URI = os.getenv('X_OAUTH_REDIRECT_URI', f'{FRONTEND_URL}/auth/x/callback')
X_OAUTH_AUTHORIZE_URL = 'https://twitter.com/i/oauth2/authorize'
X_OAUTH_TOKEN_URL = 'https://api.twitter.com/2/oauth2/token'
X_OAUTH_USER_INFO_URL = 'https://api.twitter.com/2/users/me'

# Security settings for production
if ENVIRONMENT == 'production':
    # HTTPSを強制（nginxがSSL終端を担当するため、バックエンドでは無効化）
    # Cloudflareとnginx間、nginxとバックエンド間はHTTPSだが、
    # バックエンドはnginxからのHTTPリクエストを受け取るため、リダイレクトを無効化
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    
    # nginx（プロキシ）からのリクエストを信頼
    # Cloudflare経由でHTTPSリクエストが来る場合、nginxがX-Forwarded-Proto: httpsを設定
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
