# Generated by Django 5.2.5 on 2025-11-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_groupchatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupchatmessage',
            new_name='user_messag_communi_c0907e_idx',
            old_name='user_messages_communi_g_idx',
        ),
        migrations.RenameIndex(
            model_name='groupchatmessage',
            new_name='user_messag_sender__ead5f4_idx',
            old_name='user_messages_sender_g_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='user_messag_recipie_9e8357_idx',
            old_name='user_messages_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='user_messag_recipie_0e1889_idx',
            old_name='user_messages_recipie_2_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='user_messag_communi_6048af_idx',
            old_name='user_messages_communi_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='user_messag_sender__ea3758_idx',
            old_name='user_messages_sender_idx',
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='user_messages.groupchatmessage', verbose_name='引用元メッセージ'),
        ),
    ]
