# Generated by Django 5.2.5 on 2025-11-07 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_community_clip_post'),
        ('user_messages', '0003_rename_user_messages_communi_g_idx_user_messag_communi_c0907e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', '投稿'), ('comment', 'コメント')], max_length=10, verbose_name='報告対象の型')),
                ('content_object_id', models.PositiveIntegerField(verbose_name='報告対象のID')),
                ('body', models.TextField(verbose_name='報告内容')),
                ('status', models.CharField(choices=[('pending', '未対応'), ('in_progress', '対応中'), ('resolved', '対応済み'), ('rejected', '却下')], default='pending', max_length=20, verbose_name='対応状況')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='communities.community')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['community', '-created_at'], name='user_messag_communi_a1dd2e_idx'), models.Index(fields=['community', 'status', '-created_at'], name='user_messag_communi_4f9585_idx'), models.Index(fields=['reporter', '-created_at'], name='user_messag_reporte_881fc3_idx'), models.Index(fields=['content_type', 'content_object_id', '-created_at'], name='user_messag_content_a13e32_idx')],
            },
        ),
    ]
