# Generated by Django 5.2.5 on 2025-11-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_community_clip_post'),
        ('user_messages', '0004_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessage',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_chat_messages', to='user_messages.report', verbose_name='引用元報告'),
        ),
        migrations.AddIndex(
            model_name='groupchatmessage',
            index=models.Index(fields=['report', '-created_at'], name='user_messag_report__c0547c_idx'),
        ),
    ]
